spring.application.name=carla
spring.datasource.url=jdbc:mysql://localhost:3306/canciones_db
spring.datasource.username=root
spring.datasource.password=84468446

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mvc.view.prefix=/WEB-INF/
spring.mvc.view.suffix=.jsp
